# Generated by Django 4.2.17 on 2024-12-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='avionics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_aircraft', to='production.avionicspart'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_aircraft', to='production.bodypart'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_aircraft', to='production.tailpart'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='wing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_aircraft', to='production.wingpart'),
        ),
    ]
